### ISSUE TITLE
Reader: local XSD entities possible?

### ISSUE THREAD

**Issue by netsensei** [fruux/sabre-xml#126]
An XSD schema will typically reference to external XSD entities which are hosted across the Web. Classic example is http://www.w3.org/XML/1998/namespace which has a SchemaLocation at "http://www.w3.org/2001/xml.xsd"

Validators will try to fetch the remote xml.xsd on the fly over HTTP. W3C has added traffic shaping on their side to discourage excessive HTTP requests to their XSD schemas:

https://www.w3.org/blog/systeam/2008/02/08/w3c_s_excessive_dtd_traffic/

So, we are left with caching our XML schema's locally. There are different strategies to do that. The first would be to use XML catalogs. LibXML supports these and they are stored in /etc/xml/catalog. This would be the preferable way of doing things.

An alternative use case would be implementing [libxml_set_external_entity_loader](https://secure.php.net/manual/en/function.libxml-set-external-entity-loader.php) and with a custom resolver handler. Why would you want to do that? Well, because you might be working with domainspecific schema's - such as [OpenGIS GML](schemas.opengis.net/gml/3.1.1/) - and you don't have access to the global XML catalog on the server where you host your application.

I was wondering:

1. Does XMLReader::seSchema support libxml_set_external_entity_loader and locally served xsd files? I already asserted that DOMDocument allows it.
2. Is it feasible to implement libxml_set_external_entity_loader in a separate method in the Reader class() such that it takes an associative array with references to local xsd files?

Thanks!

**Comment by evert** [comment]
Hi @netsensei ,

> Does XMLReader::seSchema support libxml_set_external_entity_loader and locally served xsd files? I already asserted that DOMDocument allows it.

Frankly, I don't know! I would assume yes, since XMLReader uses libxml under the hood, but I'm not sure. I haven't really done much with schemas myself.

> Is it feasible to implement libxml_set_external_entity_loader in a separate method in the Reader class() such that it takes an associative array with references to local xsd files?

Well, does it actually make sense to have this on the class/object level. From the function definition it seems that calling this function enables it's globally. So if there's multiple XMLReader objects doing things at the same time, calling libxml_set_external_entity_loader on one instance would definitely influence the other.

Ideally the underlying library would allow us to set this entity loader on specific instances of XMLReader, but since that's not the case, I'm also not really sure what value there would be in having this defined right on the XMLReader itself?

I hope I understood your message correctly. If not, let me know!

**Comment by netsensei** [comment]
Hi @evert,

You understood correctly, thanks! 

> Ideally the underlying library would allow us to set this entity loader on specific instances of XMLReader, but since that's not the case, I'm also not really sure what value there would be in having this defined right on the XMLReader itself?

I was thinking along the same lines since the handler both seems to affect DOMDocument and XMLReader. So, your answer confirms this for me.

Although PHP gives you the possibility, libxml2 provides support for XML catalogs. This is an XML based configuration file stored in /etc/xml which allows you to define a mapping to a set of local XSD files.  The main use cases to implement libxml_set_external_entity_loader() would be (1) you are in a context where you don't have access to /etc/xml/catalog. (2) you want to set this dynamically on runtime (for whatever reason) instead of maintaining a long, complicated mapping in a static file. 

But even then, I agree, because it works on a global level, there isn't much value in adding it to the library itself. 

Thanks! I'll close this issue.
